; ================================================================
;  PlatformIO — SmartToll Density Monitoring System v3.2.1
;  ESP32 DevKit, Arduino framework
;
;  Default build: src/multi-tab/ (multi-file variant)
;  Untuk single-tab, ganti src_dir di bawah:
;    src_dir = src/single-tab
; ================================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
src_dir = src/multi-tab
lib_deps =
    madhephaestus/ESP32Servo
    marcoschwartz/LiquidCrystal_I2C
