; PlatformIO Project Configuration
; SmartToll Density Monitoring System v3.2.1
;
; Build: pio run -e esp32dev
; Upload: pio run -e esp32dev -t upload
; Monitor: pio device monitor -b 115200

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    madhephaestus/ESP32Servo
    marcoschwartz/LiquidCrystal_I2C
